//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipBucket.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClipSpeaker
    {
        public int ClipSpeakerId { get; set; }
        public int ClipId { get; set; }
        public int SpeakerId { get; set; }
        public byte SpeakerOrder { get; set; }
    
        public virtual Clip Clip { get; set; }
        public virtual Speaker Speaker { get; set; }
    }
}
