//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipBucket.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clip()
        {
            this.ClipSpeakers = new HashSet<ClipSpeaker>();
            this.ClipTags = new HashSet<ClipTag>();
        }
    
        public int ClipId { get; set; }
        public string ClipTitle { get; set; }
        public int CategoryId { get; set; }
        public string TranscriptFile { get; set; }
        public string SubmitterId { get; set; }
        public int SourceId { get; set; }
        public int ClipLength { get; set; }
        public int MediumId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Medium Medium { get; set; }
        public virtual Source Source { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClipSpeaker> ClipSpeakers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClipTag> ClipTags { get; set; }
    }
}
